### PR TITLE
Rename master to main

### PR DESCRIPTION
**Pull request by jarrodmillman**
This is for after @rgommers renames the master branch main.

### CODE REVIEW

**Comment by rgommers** [comment]
I'd say no need to make these PRs Draft @jarrodmillman, that way they can't be merged. I'll go move master to main right now.

**Comment by rgommers** [comment]
done

**Comment by jarrodmillman** [comment]
@rgommers This is ready to merge.

**Review by rgommers — APPROVED** [review]
Thanks @jarrodmillman

**Pull request merged**
